### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by xiyuanzh** [kedayuge/Embedjoin#1]
Hi, I have read the paper Embedjoin, and the tested dataset in the statistics table that the paper mentioned seems to be quite different from the dataset in this repo. I calculated the edit distance between these strings in the repo and found the distances are generally much greater(over 1000) than the threshold K(20, 40, 100 e.g.). Could you be so nice to shed some light on the dataset difference? Thanks a lot for your kindly help!

**Comment by kedayuge** [comment]
I think fig.9 of our arxiv version would give you a good sense of our datasets (https://arxiv.org/pdf/1702.00093.pdf). Basically, most of the string pairs are dissimilar with a large distance (over 1000), but there are still a large number of similar pairs with relatively smaller edit distances (let's say < 200).  Our job is to find the most similar pairs (with ED < K) within these similar pairs.  

You can imagine the red/blue line in fig 9 represents the distribution of similar/dissimilar pairs. For instance, on TREC dataset, the similar pairs are with edit distance less than 200, and dissimilar pairs are with distances 300~1500.  Thus, we set our edit threshold on TREC at most 50 to make our task meaningful and challenging. 

You may see that on genome dataset (GEN50kS), the boundary of similar and dissimilar pairs are not very clear, which means it is even more difficult than others. That's why we conduct the ultimate scalability experiments on it and set the edit threshold as 20% of string lengths.
